### ISSUE TITLE
Dark Mode ?

### ISSUE THREAD

**Issue by jwalsh2me** [jakewies/hugo-theme-codex#100]
Is Dark Mode support an option that I missed in the `config.toml`?  I noticed you have it on your site @jakewies but I think your site is also a more modified version of the Codex theme.

**Comment by jakewies** [comment]
Hey @jakewies ! My personal site is no longer using Hugo or this theme. So no, there's no dark mode support. Sorry! If that's a feature you'd like to implement, we'd welcome a PR!
