### ISSUE TITLE
Adding new kinds of pages

### ISSUE THREAD

**Issue by WickedBrat** [jakewies/hugo-theme-codex#104]
Hi, I wanted to add a photo gallery to my [website](https://wickedbrat.com). Will that be possible?

**Comment by jakewies** [comment]
Hey @WickedBrat,

Thanks for your interest in this project! You absolutely can add new pages to the theme. You can follow the [`README`](https://github.com/jakewies/hugo-theme-codex#adding-a-new-section-menu), where we document how to add a new page. We're actually using the example `/photos`.

**Comment by WickedBrat** [comment]
Hi @jakewies 
Thanks for the directions. Yes, I see that particular example about `photos` but my question was whether we can add a different layout with a different layout. As far as I understand, this photos page would be similar to a blog page only, where we can add photos too. Please correct me if I'm wrong.

**Comment by WickedBrat** [comment]
I want to have a photos page to show the pics in a grid view. This could also open a modal to show the image in full screen. Could this be done if we tweak with the template to generate a page that generates HTML of the same grid view and take images as args via markdown?

**Comment by jakewies** [comment]
Yes you can. You can create a new layout in your own layouts directory. Hugo documentation explains how the template lookup order works. If it finds a layout for your content type it will use it instead of the theme layout.

https://gohugo.io/templates/lookup-order/

**Comment by WickedBrat** [comment]
Thanks! I will try that out :D
