### ISSUE TITLE
Various background colors are hardcoded

### ISSUE THREAD

**Issue by CER10TY** [jakewies/hugo-theme-codex#107]
I noticed that various background colors (like that of the navbar) are currently hardcoded to #fff instead of using the $white variable defined in _colors.scss (or _vars). Is this intentional?

**Comment by jakewies** [comment]
Hey @CER10TY 

No it's not intentional. If you'd like to open a PR to fix that it would be greatly appreciated! Thanks for the heads up 😊

**Comment by CER10TY** [comment]
Hey,

just opened the PR for the fix.

**Comment by CER10TY** [comment]
Hey @jakewies,

good to know! I just opened the PR, that should switch out all of the hardcoded variables.
