### ISSUE TITLE
Code highlighting not working properly

### ISSUE THREAD

**Issue by xvallspl** [jakewies/hugo-theme-codex#11]
Code blocks are illegible.

Even in a simple code block like:

```js
function(){}
```
is rendered as 

![image](https://user-images.githubusercontent.com/867299/84805894-393f5b80-b005-11ea-8eb9-9989615330d9.png)

For instance, The following C++ block

```cpp
 std::unique_ptr<TF1> f1("f1", "gaus");
 f1->SetParameters(1, 0, 1);
 
 h1->Fit(f1);
```
generates a black block (the text is still there when highlighting the line with the mouse)

**Comment by jakewies** [comment]
I noticed this yesterday. Need to debug this and see what's going on. Prism is not working properly.

**Comment by xvallspl** [comment]
I tried getting rid of prism and using the default syntax highlighting, but It didn't work either. From a quick and dirty debuggin seems that at least part of the problem is in the css (post in this case).

Might give it another look tomorrow if you can't figure it out.

**Comment by jakewies** [comment]
Ok great thanks for your help!

**Comment by russianryebread** [comment]
I generated a custom prism css file (I wanted a different template anyway) and added it to the blog template, and it worked just fine.

In `/layouts/blog/single.html`
```
{{ define "stylesheets" }}
<link rel="stylesheet" href="/css/post.css" /> 
<link rel="stylesheet" href="/vendor/prism/prism.css" type="text/css" /> 
{{ end }}
```

**Comment by jakewies** [comment]
I've actually been heads down fixing this issue for the last hour or so. There are actually a few nuances going on here.

As @russianryebread mentioned, you need a stylesheet to get things running. However, this theme includes [a custom syntax highlighting theme](https://github.com/jakewies/hugo-theme-codex/blob/master/src/styles/partials/_github-syntax-highlighting.styl), something I wrote a few years ago when I became obsessed with Github's syntax highlighting. I just couldn't find a theme that was offered by prism / highlight that could replicate it. 

It's being loaded as part of the blog post page's stylesheet. But the reason it's not showing is because of a change in [Hugo v0.60.0](https://gohugo.io/news/0.60.0-relnotes/#notes):

> - Config option for code highlighting of code fences in Markdown is now default on. This is what most people wants.

Turning that setting off will let prism take over. 

I opened https://github.com/jakewies/hugo-theme-codex/pull/16 to address this.

**Comment by jakewies** [comment]
Closing with #16

**Comment by xvallspl** [comment]
Oh, sure. But the way the theme's CSS is set up, it messes with the default style for codefences, in case the user wants to use them instead of prism.js.

**Comment by ElasticBottle** [comment]
> 
> 
> Oh, sure. But the way the theme's CSS is set up, it messes with the default style for codefences, in case the user wants to use them instead of prism.js.

Can second this about the codefences 

Is there any way to fix it // change prismjs theme?

**Comment by jakewies** [comment]
Hey @ElasticBottle! 

Just trying to understand your issue better. The point that @xvallspl made was that if users of this theme want to use the default Hugo syntax highlighting rather than `prismjs`, they will have issues because [this theme's custom syntax highlighting](https://github.com/jakewies/hugo-theme-codex/blob/master/assets/scss/partials/_github-syntax-highlighting.scss) messes with the Hugo default.

Is this what you've encountered?

If you followed the readme you should have copied over the contents of `exampleSite/config.toml`, which includes [this line](https://github.com/jakewies/hugo-theme-codex/blob/master/exampleSite/config.toml#L46). Did you remove it? I imagine you did but are still having issues, which makes sense because the custom syntax highlighting still loads whether you remove it or not.

**Comment by ElasticBottle** [comment]
Thanks so much for the speedy response!

Yeap, exactly what I encountered. 

I removed 
```
[markup.highlight]
    codeFences = false
```
from config.

Here is how the syntax highlighting looks:
![image](https://user-images.githubusercontent.com/44563205/86557395-92f1d080-bf88-11ea-8df8-6754a1cd8470.png)

I tried removing  `_github-syntax-highlighting.scss` altogether but it doesn't work. I am assuming that some where in the layouts, the css import has to be removed as well. Haven't managed to find that.

I'm open to simply changing the theming directly from `prismjs` as well, but not too sure how to go about that. 😅

**Comment by jakewies** [comment]
I've done some debugging on this and I've found the issue:

In `exampleSite/config.toml` you'll find the following:

```toml
# This disables Hugo's default syntax highlighting in favor
# of prismjs. If you wish to use Hugo's default syntax highlighting
# over prismjs, remove this. You will also need to remove the prismjs
# vendor script in layouts/blog/single.html.
[markup]
  [markup.highlight]
    codeFences = false
```

The comments say to remove this configuration if you want to use Hugo's default syntax highlighting. This is a necessary step, but doesn't get you all of the way there. As you've already seen, doing so will result in the following syntax highlighting styles:

![](https://cdn.discordapp.com/attachments/724652167885226014/729754577041358898/Screen_Shot_2020-07-06_at_1.44.59_PM.png)

Not ideal. The next step I took was to look in [`assets/scss/pages/post.scss`](https://github.com/jakewies/hugo-theme-codex/blob/master/assets/scss/pages/post.scss). There is an import statement that brings in the custom syntax highlighting for the theme:

```scss
// assets/pages/post.scss

@import "../partials/github-syntax-highlighting"
```

I commented out this import statement and tested again. I was met with the following visual:

![](https://cdn.discordapp.com/attachments/724652167885226014/729754572884672552/Screen_Shot_2020-07-06_at_1.45.22_PM.png)

Again, not ideal. The next and final step was to peak into the post's layout file and remove the `prismjs` script. When I did that, I was getting the desired syntax highlighting:

![](https://cdn.discordapp.com/attachments/724652167885226014/729754558884216922/Screen_Shot_2020-07-06_at_1.45.41_PM.png)

So the steps needed to get Hugo's default syntax highlighting to take over is:

1. Remove the `codeFences = false` configuration in `config.toml`
2. Remove the `@import "../partials/github-syntax-highlighting"` in `assets/scss/pages/post.scss`
3. Remove the `prismjs` script in `layouts/_default/single.html`

Obviously, the steps above are not convenient for the user. We'll need to find a better abstraction for all of this. It seems there is a need for it.

**Comment by jakewies** [comment]
I'm going to work on a PR that will hopefully remove this issue for people. If users want to opt into Hugo's default syntax highlighting they should be able to through an easy config. That's goal at least.

**Comment by ElasticBottle** [comment]
Interesting, I tried the step above and ended up with this:
![image](https://user-images.githubusercontent.com/44563205/86724990-db2df300-c05b-11ea-93f9-0ab5d910045e.png)

I tried digging a little deeper and noticed about the asset under resources, removing the scss file `post.scss_9b5a08989dabcb86a5d520fc24aa3741.content` results in proper highlighting but no more formatting

![image](https://user-images.githubusercontent.com/44563205/86725296-1b8d7100-c05c-11ea-99ff-8ae3a48f943d.png)

I supposed there might be a way to regenerate the assets? I'm still very new to Hugo, will continue looking around

**Comment by jakewies** [comment]
Interesting. This could have something to do with https://github.com/jakewies/hugo-theme-codex/issues/69. 

I did my testing using our development workflow, where I was able to see style changes to the `exampleSite` demo when editing the source `scss` files. But you are probably using the theme as most people would, i.e. adding it as a `git submodule`. Am I correct?

**Comment by ElasticBottle** [comment]
Yup, exactly right, I have been playing around with the site, but am still pretty lost.

There doesn't seem to be many documentation on Hugo pipes and generating resources 😞 

Initially, I copied the `resource/_gen` folder over from the `exampleSite`.

Looking at #69 that you mentioned, 

In particular, I tried:

>* From the root of a Hugo project that uses your theme execute the command hugo server -this will generate the /resources/ folder under the project root-.
>* Or if you prefer to build the project simply run the command hugo -this will generate the resources under public/resources-.
>* Copy the generated resources folder and commit it directly either under the root of your theme's repository or under exampleSite.

However, for `hugo server`, the resource folder generated contains two empty folder `assets` and `js`.

For `hugo`, the generated `public` folder did not contain any generated resource whatsoever.

Feel free to point me in resources for generating resources, I'll try digging more into it.

Also, being pretty lost, I tried replacing the generated content directly with the contents from the `post.scss` but I'm assuming there needs to be some pre-proccessing to combine all the imports and then translate the `.scss` file to `css`

**Comment by kentnek** [comment]
> Initially, I copied the resource/_gen folder over from the exampleSite.

hmm you're not supposed to copy the `resources/_gen` folder from the `exampleSite`, as it's only a cache for the demo to work.
Running `hugo serve` should _theoretically_ generate your site's own `resources/_gen` folder.

I tried cloning your [blog project](https://github.com/ElasticBottle/winykh) (hope you don't mind) and the `resources` folder was generated properly with `hugo serve`. 

![image](https://user-images.githubusercontent.com/7024160/87228146-c17d0a80-c3d1-11ea-8213-9d7138e3f25c.png)

May I check if you are using the `hugo-extended` version? As it is needed to transpile `scss` into `css`.

**Comment by kentnek** [comment]
> I'm going to work on a PR that will hopefully remove this issue for people. If users want to opt into Hugo's default syntax highlighting they should be able to through an easy config. That's goal at least.

@jakewies I got an idea to achieve this elegantly. Currently, each page is defining its own stylesheet using the `style_opts` in Hugo's Scratch. We can extend this to accept a list of styles, so that for the `single.html` template, we could conditionally add in the custom syntax highlighting stylesheet if people opt for `prism.js`. 

I can work on this :)

**Comment by jakewies** [comment]
Hey @kentnek sorry I've been a bit busy IRL. I like this idea you've proposed. If you want to give it a shot go for it!

**Comment by ElasticBottle** [comment]
>May I check if you are using the hugo-extended version? As it is needed to transpile scss into css.

Right on point, I had both the normal hugo version and the `extended` version installed, seems to be some conflict going on.

After rebuilding, I followed @jakewies  steps as mentioned and everything worked perfect


>  1. Remove the codeFences = false configuration in config.toml
>  2. Remove the @import "../partials/github-syntax-highlighting" in assets/scss/pages/post.scss
>  3. Remove the prismjs script in layouts/_default/single.html

I might add that 4. remove `resource` folder, close any open hugo development servers and run `hugo serve` again to generate the `resource` folder files

Thanks so much for the active maintenance of the site!

**Comment by kentnek** [comment]
@ElasticBottle I'm glad it's working for you! I guess we need to make the mention of `hugo-extended` **bolder** in the README 🤣

also I'll work on a PR so that you don't have to manually do @jakewies's suggestions anymore. I'll close this issue first, and let you know later when that PR is live.
