### ISSUE TITLE
Table of Contents adds overflow in mobile view

### ISSUE THREAD

**Issue by CER10TY** [jakewies/hugo-theme-codex#112]
Hi,

I noticed that the TOC adds a bit of overflow when viewing any blog post on mobile, since the TOC is set to `visibility: hidden` instead of `display: none`.

**Comment by jakewies** [comment]
Hey @CER10TY thanks for raising this issue. I just attempted to reproduce and I can see the issue. I'm going to submit a PR to get this fixed. I appreciate it!

**Comment by sdil** [comment]
thank you @jakewies for the fix! It works perfectly fine on my blog now :D
