### ISSUE TITLE
Add support for Admonitions

### ISSUE THREAD

**Issue by xvallspl** [jakewies/hugo-theme-codex#119]
It would be really nice to have support for Admonitions: https://gohugo.io/contribute/documentation/#admonitions

I personally like the style and variety of the mkdocs Material theme, but I don't know about their fit with codex: https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types

I won't have time to look at this for a while, so I leave it here just in case someone else wants to give it a try before I do :)

**Comment by jakewies** [comment]
@xvallspl this looks like a feature out of the scope of this project. Going to close.
