### ISSUE TITLE
Adding Description under the blog titles

### ISSUE THREAD

**Issue by SirCharan** [jakewies/hugo-theme-codex#124]
Is there a way to add a description under the blog titles in the /blog?
![image](https://user-images.githubusercontent.com/48174619/92307758-40e42000-efb6-11ea-8a40-cc16048b988d.png)

Something like whats present in Ramium?

**Comment by jakewies** [comment]
Hey @SirCharan , there's been an open PR (https://github.com/jakewies/hugo-theme-codex/pull/75) for this feature for a few months now, but it has gone pretty stale and I don't have much time to work on it at the moment. If there were more support for this I'd do my best to make it a priority but it doesn't seem to be.

That being said, if you'd like to take a peak at the PR and see how it's done, you could integrate with your own project. If you'd like to contribute this feature to this project / take over that PR that would be most welcome.
