### ISSUE TITLE
Issue with ordering

### ISSUE THREAD

**Issue by arjitsrivastava** [jakewies/hugo-theme-codex#127]
Hey everyone.

Firstly, thank you for creating and maintaining this Hugo theme. I've been having fun playing with the content and the theme, in general. 💯  

But, there's something silly I've been struggling with and failing to figure out what's the root cause for it. So for instance, here's the ordering which I can see locally on my machine when I build.

![Screenshot 2020-09-30 at 11 17 16 AM](https://user-images.githubusercontent.com/9508440/94647675-95a55d00-030e-11eb-9ab4-d58c4248e51a.png)

However, this is the ordering which gets deployed (I use Vercel).
![Screenshot 2020-09-30 at 11 17 02 AM](https://user-images.githubusercontent.com/9508440/94647662-90481280-030e-11eb-92f9-6321f0b5c9ca.png)

I'm sure it's got to be something trivial, but I'm currently failing to figure out the exact issue. Has someone faced this before? I can share the link to the hosted website, too, if that helps.

**Comment by jakewies** [comment]
Hey @arjitsrivastava , this looks like an issue with the structure of your content and not specifically with the theme itself. You might want to check the Hugo docs and see if you're rendering a list of items properly.
