### ISSUE TITLE
Add a new homepage-like page

### ISSUE THREAD

**Issue by WickedBrat** [jakewies/hugo-theme-codex#130]
I want a new page that is more like a homepage. But I'm unable to do that by creating a `_index.html` file.

I want to have a section in the middle of the page (same as the homepage) but I want that to be on a different page and just a paragraph of text.

**Comment by jakewies** [comment]
Are you wanting to override the current homepage? Or create a completely new page that looks like the homepage?

If you are looking for the former, you can simply override the default layout. [See the README](https://github.com/jakewies/hugo-theme-codex#configuring-the-home-page) for more info.

If you are looking for the latter, you would just need to add a new page to your site following Hugo's guidelines. The lookup order will make sure to take your page into account.
