### ISSUE TITLE
JS/CSS files in the static directory are being marked as modified by git

### ISSUE THREAD

**Issue by jakewies** [jakewies/hugo-theme-codex#14]
Not yet sure why this is happening. Probably something to do with the way gulp is writing the files from their source.

**Comment by jakewies** [comment]
Quick update on this issue:

When the npm script `yarn watch:assets` is triggered, sourcemaps are added to the generated css files. This causes git to mark the css files as "modified", even though source code hasn't changed. This can be an annoyance. Why? Well, if you're developing on this project, every css file will be marked as modified as soon as you run `yarn watch:assets`, cluttering up your git status. 

Possible solutions

1. Remove sourcemaps in development
2. Use git hooks to build the static directory before a commit. This would result in the css files being stripped of their sourcemaps
3. Add the `/static` directory to `.gitignore` 

No. 1 is the easiest solution but would result in worse dev experience

No. 2 I've done in other projects before using a tool like [`husky`](https://github.com/typicode/husky), but it would require that the css files be staged (I think), which defeats the purpose. 

No. 3 My ideal solution, but this would require that the `/static` directory gets produced at some point when a potential contributor / user downloads the project. I'm sure there is a way to do this with git hooks / npm scripts, I'm just not aware of a solution at this time.

**Comment by kentnek** [comment]
Hmm how about using SASS/SCSS as Hugo [can support it natively](https://gohugo.io/hugo-pipes/scss-sass/) without using other tools like gulp? This way we only need to include the source scss files, while the output css is generated by hugo itself while serving/building.

**Comment by jakewies** [comment]
I wasn’t aware of Hugo’s native support. I actually really like this. It removes the need to have build step at all. If you consider what’s actually being done with gulp....it’s overkill. We can move the very limited JS to the static directory completely, images/icons as well, and write styles in scss/sass. 

.... I dig on it.

**Comment by kentnek** [comment]
^ Another theme that I used previously uses scss and the folder structure is super nice, with support for a `custom.scss` for users to add in their own styles. I'm actually translating my fork to scss so I'll take this issue.

**Comment by jakewies** [comment]
> Nevertheless, I think git marking the generated css/js files as "modified" is not a problem, because well, they are _generated_ and subject to changes when the source stylus files are modified. 

If this were the case then I’d agree,  but the problem is that the source stylus files can remain unchanged and gulp will still append sourcemaps on the output css files if you run `yarn watch:assets`. 

Take this as an example:

You clone the repo and want to make a change. You install deps and then decide to run `yarn watch:assets` before getting to work. As soon as the command runs, git will say that every css file in the `/static` directory is “modified”, even though the source files were never touched. It’s the sourcemaps that are appended which causes the files to suddenly become modified.

**Comment by jakewies** [comment]
@kentnek go for it!

**Comment by kentnek** [comment]
> the problem is that the source stylus files can remain unchanged and gulp will still append sourcemaps on the output css files

oh ouch I wasn't aware of that. But yeah switching to SCSS/SASS will fix this issue too so yeah we can shoot two birds with one stone haha

**Comment by jakewies** [comment]
And remove some dependencies! Big win. I'm going to read up on style support for Hugo. I'm just curious.

There was no real reason for me to use stylus. I was kind of fascinated by its creator due to their prolific nature, but at this point its just not a need.

**Comment by jakewies** [comment]
Closing with #33 great work @kentnek !
