### ISSUE TITLE
serve error - MediaType.Suffix

### ISSUE THREAD

**Issue by ragozzine** [jakewies/hugo-theme-codex#165]
Hello!

Starting today (Mar 23, 2021) I started getting this local error with `hugo serve`:

`Failed to render pages: render of "home" failed: "/Users/ragozzine/web/laboratory/fishex/themes/hugo-theme-codex/layouts/_default/baseof.html:41:95": execute of template failed: template: index.html:41:95: executing "index.html" at <.MediaType.Suffix>: can't evaluate field Suffix in type media.Type`

In the file, if I pull this chunk of code out, the serve works without issue:

```
{{ range .AlternativeOutputFormats }}
  {{ printf `<link rel="%s" type="%s+%s" href="%s" title="%s" />` .Rel .MediaType.Type .MediaType.Suffix .Permalink $.Site.Title | safeHTML }}
  {{ end }}
```

**Comment by soZra** [comment]
I got the same problem and I guess you might have upgraded to Hugo 0.82 as I did. I found in the Hugo 0.82 release note that they've moved `MediaType.Suffix ` to `MediaType.FirstSuffix.Suffix `. Then I  replaced it in `hugo-theme-codex/layouts/_default/baseof.html` and it worked.

**Comment by ragozzine** [comment]
Great tip. I suggested such a change to the theme in https://github.com/jakewies/hugo-theme-codex/pull/166

**Comment by 1-whateveruwant** [comment]
THX @soZra it works!

**Comment by rahulmkhj** [comment]
Thank you @soZra , you're a champ! :)

**Comment by rigille** [comment]
thanks @soZra!

**Comment by 2keebs** [comment]
Absolute champ! Been trawling through the net trying to solve this and didn't realise it might've been an issue with the theme itself. Cheers mate @soZra

**Comment by PyronoidDev** [comment]
Just had this problem while deploying my site with a build server and found that setting an environment variable of `HUGO_VERSION` to "0.80.0" is a good fix for people who are deploying with a similar system to mine (DigitalOcean App). Hope this helps anyone else struggling with a similar problem!

Great theme, by the way!

**Comment by jakewies** [comment]
Hey all, sorry for the delayed response on this! 

So this issue looks like it is plaguing many newcomers to the theme when they are running the most recent version of Hugo. The fix in https://github.com/jakewies/hugo-theme-codex/pull/166 looks like it should solve it, but that would also mean anyone using Hugo versions < 0.82 would run into issues.

@PyronoidDev your fix would definitely help those on DigitalOcean override the Hugo version manually, but if https://github.com/jakewies/hugo-theme-codex/pull/166 is merged in you shouldn't need the override anymore.

**Comment by jakewies** [comment]
To everyone still following this issue, @altescape has created https://github.com/jakewies/hugo-theme-codex/pull/176 which I have now merged and should resolve this. Thanks again @ragozzine !
