### ISSUE TITLE
Add a demo link for Codex

### ISSUE THREAD

**Issue by TeoDev1611** [jakewies/hugo-theme-codex#175]
Hi 👋🏼 you can provide a demo link for preview the theme. The demo link on the repository information is broken 

> That link 
![image](https://user-images.githubusercontent.com/73144037/123303148-19c5f300-d4e3-11eb-8ded-e485ea1e4c54.png)

Thanks

**Comment by jakewies** [comment]
@TeoDev1611 I believe the demo link is broken because we were not passing Hugo's official theme requirements. My best guess is that https://github.com/jakewies/hugo-theme-codex/issues/165 was causing the issue. It has since been resolved and I'll look into getting a demo link up.

**Comment by jakewies** [comment]
I've drafted up a new [release](https://github.com/jakewies/hugo-theme-codex/releases/tag/v1.6.0). This should hopefully prompt the Hugo Themes Builder to pull from our latest codebase and correctly build the demo. More info can be found [here](https://github.com/gohugoio/hugoThemesSiteBuilder/blob/main/README.md#faq).
