### ISSUE TITLE
Add more social icons?

### ISSUE THREAD

**Issue by kentnek** [jakewies/hugo-theme-codex#31]
More social icon SVGs, such as Instagram, LinkedIn and email, can be added.

**Comment by jakewies** [comment]
We could definitely support more social icons natively. I've seen examples in the wild of others who have expanded upon what this project includes (github/twitter). 

cc @chuxinh - maybe you have some input on how you accomplished this?

**Comment by kentnek** [comment]
@jakewies oh I thought you were using some ready-made icon packs for the existing GitHub/Twitter icons. I guess I'll use some free "outline social icon packs" for my fork then.

**Comment by chuxinh** [comment]
@kentnek The current theme is a bit tedious in terms of adding social icons. My site is achieved by the following:
- Have a partial of `social-icons.html`
- define social icons in the partial like below:
```html
<div class="social-icons">
  <a class="social-icons__icon social-icons__icon--email" href=""></a>
  <a class="social-icons__icon social-icons__icon--twitter" href=""></a>
  <a class="social-icons__icon social-icons__icon--github" href=""></a>
  <a class="social-icons__icon social-icons__icon--instagram" href=""></a>
  <a class="social-icons__icon social-icons__icon--linkedin" href=""></a>
</div>
```
To render those icons properly, you need to modify or add in the css. I saved all svgs in a file under `static/icons`
```css
.social-icons__icon--twitter {
  background-image: url("/icons/twitter.svg");
  margin-right: 1rem;
}
```
And then you can use those partials anywhere needed. Hope that helps!

**Comment by kentnek** [comment]
@chuxinh oh my problem is actually finding the SVGs. May I know where you obtain the SVGs for other icons?

**Comment by chuxinh** [comment]
@kentnek there's a good site for you looking for SVGs: https://www.flaticon.com/
Can use those free one for both personal and commercial  use.

**Comment by jakewies** [comment]
@kentnek i believe the icons I used were from https://feathericons.com/

**Comment by kentnek** [comment]
@jakewies oh awesome this is exactly what I need. I'll add in some more icons after finishing the SCSS PR.

**Comment by jakewies** [comment]
We could open a PR to add some svg icons from feather that cover "most" use cases, and they can be optional based on configuration setup that we decide on.

**Comment by kentnek** [comment]
^ Yep, I'm also thinking that way.

**Comment by jakewies** [comment]
Closing with https://github.com/jakewies/hugo-theme-codex/pull/40
