### ISSUE TITLE
Reference to an email social icon in README

### ISSUE THREAD

**Issue by jakewies** [jakewies/hugo-theme-codex#34]
I noticed that there is a reference to adding an email social icon in [the README](https://github.com/jakewies/hugo-theme-codex/blame/master/README.md#L62). @chuxinh was this a mistake? I don't think the theme supports this at the moment. If it is I'll go ahead and remove it for the time being.

**Comment by chuxinh** [comment]
Not really a mistake here as it's the current manual way of adding email and other social icons. However they do need to find their own SVGs to make it work. Do you think we should remove that for now as it's not very customisable?

**Comment by jakewies** [comment]
Oh ok I gotcha. I will update the docs to make it clear the user has to bring their own svg. I read it as if the theme supports an email icon as long as I follow those steps. Which is true up until the point of actually adding the icon.

**Comment by jakewies** [comment]
We’ll have a more configurable solution in the future too.

**Comment by jakewies** [comment]
Closing with https://github.com/jakewies/hugo-theme-codex/pull/40
