### ISSUE TITLE
Do we need to document the usage of hugo extended for scss support?

### ISSUE THREAD

**Issue by jakewies** [jakewies/hugo-theme-codex#35]
This is a question for @kentnek . I know in the README there is now a prerequisites section saying that users need the "Hugo extended" version. I didn't know this was a thing. Initial googling doesn't present a clear picture for me and I'm afraid others may have the same issue.

Should we document how to use the extended version a little better? Or is this a non-issue?

**Comment by kentnek** [comment]
Hmm most other themes that I have used don't elaborate further either. And actually when I installed Hugo for the first time, the Hugo website also mentioned that to use SCSS, install the extended version:
![image](https://user-images.githubusercontent.com/7024160/85328984-41673180-b504-11ea-9f60-b9e9608df0fd.png)

But yeah, I can explain a bit more in the documentations, but it's not a major issue IMO as most Hugo users nowadays are aware of the extended version.

**Comment by kentnek** [comment]
Oh lol actually for MacOS users, the extended is [installed by default](https://github.com/gohugoio/hugoDocs/issues/823). 🤣

I'll add some docs for Windows users like me then.

**Comment by jakewies** [comment]
Closing with https://github.com/jakewies/hugo-theme-codex/pull/39
