### ISSUE TITLE
Add theme's url to the repo's about section

### ISSUE THREAD

**Issue by kentnek** [jakewies/hugo-theme-codex#41]
@jakewies Could you add `https://themes.gohugo.io/hugo-theme-codex/` as this repo's website? That way the link will appear in the About section, making it easier to go to the demo page.

![image](https://user-images.githubusercontent.com/7024160/85412327-0b758c00-b59c-11ea-87e7-80a225b265ee.png)

**Comment by jakewies** [comment]
Oh ya def a good idea!

**Comment by jakewies** [comment]
Done

**Comment by kentnek** [comment]
Oh I just noticed there's an extra slash in the url:

![image](https://user-images.githubusercontent.com/7024160/86561207-b752aa80-bf92-11ea-842e-18da96bfde37.png)

**Comment by jakewies** [comment]
Super weird behavior here. If you go to:

```
https://themes.gohugo.io/theme/hugo-theme-codex
```

It will work just fine. However, any future navigation you make around the site will result in that 2nd slash being injected into the url. I have no clue why. It's not just our theme that does this. It seems to be a common thing on all themes. I'll make the adjustment anyway 👍
