### ISSUE TITLE
Add support for post's table of contents

### ISSUE THREAD

**Issue by xvallspl** [jakewies/hugo-theme-codex#6]
Hi! Loved your theme and I want to use it for my blog. Thanks for opensourcing it :)

I am missing what I consider a very important feature for long posts, and that's the table of contents. This should be easy to implement as you can generate it with `{{.TableOfContents}}`, but getting it to fit perfectly with the style of the blog might be a challenge, and I'm definitely not a designer.

I don't know if this sounds right to you, but having an table of contents fixed on the right hand side could enhance the navigation and usability. It could even be optional for each post.

**Comment by jakewies** [comment]
That sounds like a great idea @xvallspl! Would you like to give it a shot? We can work on the design together.

**Comment by xvallspl** [comment]
Sure, I will give it a start.

**Comment by jakewies** [comment]
Hey @xvallspl, not sure if you started on this yet. I just thought of an interesting design that could work well. If you go to the `/blog` route on a desktop you can see the tags available on the right hand side. This text is styled with gray as the color, and it's situated on the right hand side of the screen.

If a post optionally opts into table of contents, we could render it in the same spot that the blog tags render on `/blog``. Using the same styles like gray text etc.

On mobile the table of contents would hide or adjust to a collapse-able table of contents at the top of the blog post.

What do you think?

**Comment by xvallspl** [comment]
I still haven't started, but that's what I was thinking about. However, I would like to keep the post centered, and the table of contents darker than the tags.

**Comment by xvallspl** [comment]
@jakewies I had in mind something like this, but it still needs some tweaking (maybe a lot on the design side) http://xvallspl.github.io/blog/cern/analysischain/

I'll try to get a PR ready with the functionality ASAP

**Comment by jakewies** [comment]
Love it. Just keep in mind the width of the contents and maybe decided to hide it at <700px or something like that. Then it could be toggled underneath the page title.

**Comment by xvallspl** [comment]
Yeah, It's already there at 800px IIRC

**Comment by xvallspl** [comment]
Opened PR https://github.com/jakewies/hugo-theme-codex/pull/10 regarding this

**Comment by jakewies** [comment]
Closing with https://github.com/jakewies/hugo-theme-codex/pull/10
