### ISSUE TITLE
Clickable elements too close together

### ISSUE THREAD

**Issue by aareet** [jakewies/hugo-theme-codex#60]
Hi there, thank you for this theme - I am a fan! 

I've set up the theme on my website, where I have Google Search Console enabled to work on the SEO of the site. Google sent me an email after I switched to this theme with the following issue: "Clickable elements too close together". I believe they're referring to the items in the sidebar and the social icons. Just wanted to report the issue to see if you could help resolve it.

Thanks!

<img width="675" alt="Screen Shot 2020-06-29 at 12 57 32 PM" src="https://user-images.githubusercontent.com/33654/86050074-19963300-ba08-11ea-9f18-344618e9d728.png">

**Comment by kentnek** [comment]
Strange, I don't think the items on the sidebar/social icons are too close together, especially on the mobile version:

<p float="left">
<img src="https://user-images.githubusercontent.com/7024160/86144775-acc68a00-bb28-11ea-96d9-4ba12a299486.png" height="400px">
<img src="https://user-images.githubusercontent.com/7024160/86144792-b18b3e00-bb28-11ea-9960-96154589a2aa.png" height="400px">
</p>

Is it possible for Google Search Console to pinpoint exactly which element is triggering the warning?

**Comment by aareet** [comment]
Yes, I was confused as well since it's not visually apparent. Clicking on the error just takes me to

https://support.google.com/webmasters/answer/9063469#touch_elements_too_close

```
Clickable elements too close together
Touch elements, such as buttons and navigational links, are so close to each other that a mobile user cannot easily tap a desired element with their finger without also tapping a neighboring element. To fix these errors, make sure to correctly size and space buttons and navigational links to be suitable for your mobile visitors. Read more in Size Tap Targets Appropriately.
```

Maybe it has something to do with "Size Tap Targets"

**Comment by kentnek** [comment]
> Maybe it has something to do with "Size Tap Targets"

@aareet hmm that's interesting. I also notice that the social icons are a bit small too tap on, perhaps some padding would be good. Would you be able to apply this fix on your fork/site (by overriding `customs.scss`) and help us check if doing so would resolve the warning from Google Console?

**Comment by aareet** [comment]
I added `padding: 16px;` to the social icons and it passed the initial quick validation of the search console. I found this article https://web.dev/accessible-tap-targets/ that recommends touch targets have 8px padding horizontally and vertically. I'll report back on the full validation but it seems to be as simple as that to fix it.

**Comment by kentnek** [comment]
@aareet this is great news! If things go well, please submit a PR for this. Thanks so much for looking into this issue!

**Comment by aareet** [comment]
Unfortunately no dice. I'll keep trying padding on the other elements on the page

<img width="659" alt="image" src="https://user-images.githubusercontent.com/33654/86304640-5c9d0580-bbc4-11ea-8aab-78d045951289.png">

**Comment by jakewies** [comment]
It's odd that google can't tell you which items are too small. It would be helpful.

The social icons are REAL SMALL:

![Screen Shot 2020-07-01 at 9 52 54 PM](https://user-images.githubusercontent.com/12075916/86307525-f5437d80-bbe4-11ea-99d9-52421206e858.png)

I can't think of anything else, unless there is something going on with the way the mobile menu is built. I'm thinking maybe an element is hidden in a way that doesn't hide it directly in the DOM and google is complaining. I doubt this is a problem, but I did think about it.

**Comment by aareet** [comment]
Hmm yes, the article does seem to indicate 24x24 should be the minimum size of a touch target so maybe the 19x19 isn't cutting it - 

```A minimum recommended touch target size is around 48 device independent pixels on a site with a properly set mobile viewport. For example, while an icon may only have a width and height of 24px, you can use additional padding to bring the tap target size up to 48px. The 48x48 pixel area corresponds to around 9mm, which is about the size of a person's finger pad area.```

I'll try playing around with size and padding.

**Comment by aareet** [comment]
Ok, I got it working with the following in custom.scss. `padding: 24px;` worked where `padding: 16px;` did not.

<img width="596" alt="Screen Shot 2020-07-03 at 2 37 11 PM" src="https://user-images.githubusercontent.com/33654/86498430-af003280-bd3a-11ea-9876-705f7653b14a.png">


```css
  .social-icons {
    display: flex;
    justify-content: center;
  }
  
  .social-icons__icon {
    width: 1.5rem;
    height: 1.5rem;
    background-size: contain;
    background-repeat: no-repeat;
    padding: 24px;
  
    &:not(:last-child) {
      margin-right: 3em;
    }
  }
```

**Comment by jakewies** [comment]
@aareet awesome work. Would you like to open a PR to make this fix?

**Comment by kentnek** [comment]
@jakewies Oh I didn't realize this was already merged. Aren't the icons a bit too big now? 😄

> I also notice that the social icons are a bit small too tap on, perhaps some padding would be good.

What I meant was to add some blank space (padding) around the icon that is also click/tap-able to increase the icon's click/tap region. 

Currently the class `.social-icons__icon` is applied to the `<a>` element directly, which has the icon SVG as the background. This means adding `padding` to this class will make the icon background expand too, which is not ideal. I think we can put the SVG as a separate element inside the `<a>` so it won't expand due to the padding.

![image](https://user-images.githubusercontent.com/7024160/86541561-7762d780-bf40-11ea-9673-9874e3087cde.png)

![image](https://user-images.githubusercontent.com/7024160/86541565-7c278b80-bf40-11ea-9f5e-e43e72673492.png)

**Comment by kentnek** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/7024160/86541709-8c8c3600-bf41-11ea-8019-201ea56b8a80.png)

**Comment by jakewies** [comment]
@kentnek you’re right they are bigger than I realized. I should’ve caught that. With just the changes to the padding we can keep the same icon size but increase their clickable surface.

**Comment by jakewies** [comment]
@aareet with @kentnek 's latest change we should have the same visual icon styles as before but with a larger clickable surface area. If you wouldn't mind checking these changes when you have some time and let us now how it affects the results in Google Search Console we can move forward and close this issue 😄

**Comment by kentnek** [comment]
Oh I actually forgot to make the icon's padding a variable so we don't have to manually change the negative `left-margin` of the icon row on the about page. After @aareet can verify if GSC is happy with this, I'll make another PR to make the padding a variable.

**Comment by aareet** [comment]
I've updated the site, let's see what Google says 🙏

**Comment by jakewies** [comment]
@aareet I'm going to close this issue for now. If your problem persists we can reopen 😄

**Comment by aareet** [comment]
Just to confirm, no complaints from Google Search Console since the updates.

**Comment by kentnek** [comment]
awesome, thanks for the confirmation @aareet!
