### ISSUE TITLE
Build assets automatically for exampleSite

### ISSUE THREAD

**Issue by kentnek** [jakewies/hugo-theme-codex#69]
After #62, which adds the `resources/_gen` folder back to the `exampleSite`, we should re-generate those resources whenever there's a style change, so the demo site can reflect those changes properly. 

@jakewies I'm not sure what the available git hooks are for this project, any thoughts?

**Comment by jakewies** [comment]
We're using [`husky`](https://github.com/typicode/husky) for easier git hook integration. In the docs there is [a link to the supported hooks](https://github.com/typicode/husky#supported-hooks).

That should work out for us, however I'm still unsure how to re-gen the `resources/` dir other than running `hugo server`. Is there another way?

**Comment by kentnek** [comment]
from the themes repo:
>- From the root of a Hugo project that uses your theme execute the command `hugo server` -this will generate the `/resources/` folder under the project root-.
>- Or if you prefer to build the project simply run the command `hugo` -this will generate the resources under `public/resources`-.
>- Copy the generated resources folder and commit it directly either under the root of your theme's repository or under `exampleSite`.

I think we can run `hugo`, get the `resources` from `public/` and place the generated folder in `exampleSite/`.

**Comment by jakewies** [comment]
Ya the could definitely work. We can create an npm script that takes care of this. But we wouldn't need to rebuild the `resources` directory unless changes have been made to the source `scss` files, right?

**Comment by kentnek** [comment]
yep, is this possible with `husky` to only run some script selectively, i.e. when that `scss` folder is modified?

**Comment by jakewies** [comment]
Yes indeed. In our `package.json` we have this:

```json
"husky": {
  "hooks": {
    "pre-commit": "lint-staged"
  }
}
```

This config says "run [`lint-staged`](https://github.com/okonet/lint-staged) on the pre-commit hook". `lint-staged` is a tool that we have as well to run scripts on staged files. You can see our `lint-staged` config in `package.json` as well:

```json
"lint-staged": {
  "*.{js,css,scss}": "prettier --write"
}
```

Right now `husky` and `lint-staged` are working together to do one thing, and that is to run `prettier --write` on any `.js`, `.css`, and `.scss` file that has been staged for commit _just_ before they commit.

We can add another key->value pair to identify if a `scss` file has been staged for commit and run a script if it has. Something like:

```json
"lint-staged": {
  "*.{js,css,scss}": "prettier --write",
  "*.scss": "some-script-that-generates-resources-dir"
}
```

I will work on this 👍

**Comment by jakewies** [comment]
@kentnek I've been working on this issue today and I am trying to find the best solution. Correct me if I'm wrong here, but I think rebuilding the `resources/_gen/scss` directory is only necessary in scenarios where you make a change to a source `assets/scss` file but don't run `hugo`.

In general, if `hugo` is running at any point during the change, or after, the `resources` directory gets re-built. But if you simply make the change without running `hugo`, the `scss` file makes into version control but not the re-built `resource`.

Now we could simply identify whether an `scss` file is being staged for commit, and if it is we can rebuild the `resources` directory, **but** if you are running something like `yarn develop`, or decide to run `hugo` after the change, the rebuilt will already happen. So rebuilding again becomes redundant. We can still do this for the sake of completion, I just wanted to bring that up.

Let me know if you're picking up what I'm putting down.

**Comment by kentnek** [comment]
> is only necessary in scenarios where you make a change to a source assets/scss file but don't run hugo

Hmm actually doing this still requires the contributor to manually check in the changed `resources` directory. After pondering on this more carefully, I think we can just request contributors to commit the `resources` dir if during review we see that they make changes to the `scss`. 😂

**Comment by jakewies** [comment]
I agree. I was prepping a git hook buts it's a hassle. I can update contributors.md file to express this clearly.
