### ISSUE TITLE
Fix Nav-Links

### ISSUE THREAD

**Issue by somaniarushi** [jakewies/hugo-theme-codex#7]
Right now, the navigation links in the top-right corner `about` and `blog` lead to `/blog` and `/blog/blog` respectively and thus do not work correctly.

**Comment by jakewies** [comment]
Hey @somaniarushi ! Could you give me a quick step-by-step to replicate this issue?

I ran the [example site](https://github.com/jakewies/hugo-theme-codex/tree/master/exampleSite) and had no issue. Is this happening to you when you start a bootstrap a new project with `hugo-theme-codex` as your set theme?

**Comment by somaniarushi** [comment]
Hey Jake, completely my bad –– it was a problem with setting the base URL. If you set it with a /xxx, the nav links add that to the nav burger. Sorry about that!
