### ISSUE TITLE
Code blocks break responsive view on mobile

### ISSUE THREAD

**Issue by msfjarvis** [jakewies/hugo-theme-codex#79]
I'm currently migrating my site to this theme, and running into a problem where pages with code blocks are just a tad bit too wide for the viewport and mess up the layout. I'm enlisting all the information I believe would be useful below.

- Source: https://github.com/msfjarvis/msfjarvis.dev/tree/codex
- Live version: https://staging.msfjarvis.dev
- Affected pages: https://staging.msfjarvis.dev/posts/simple-tricks-for-faster-rust-programs/, https://staging.msfjarvis.dev/posts/switching-my-email-to-purelymail/ and all other pages with code blocks.
- Changes to default layouts: `baseof.html` was edited to replace the default Twitter card metadata with [hugo-social-metadata](https://github.com/msfjarvis/hugo-social-metadata). `single.html` was edited to replace disqus with my [Commento partial](https://github.com/msfjarvis/msfjarvis.dev/blob/codex/layouts/partials/commento.html). `browse-by-tag` was overriden to instead list categories.

I've reset the theme layouts to their `hugo-theme-codex` versions in [this](https://msfjarvis.dev/g/msfjarvis.dev/b4d2bf441ac1) commit so you can see exactly what changes I had made.

I have also tried [disabling pygments](https://msfjarvis.dev/g/msfjarvis.dev/bf1e348ca31b) to no benefit.

**Comment by kentnek** [comment]
Hi, I did notice this bug and I had somewhat a fix for it on [my personal site](https://kentnek.com/geek/2020/07/yacht-yet-another-compilation-of-hugo-tricks/), where code blocks can be scrolled horizontally when they're too wide.

I haven't submitted that to this repo yet because it requires some changes to the core styles, but I'll work to make it a PR soon.

**Comment by jakewies** [comment]
Hey @msfjarvis ,

Thanks for setting up an official issue for this. It definitely has something to do with codeblocks. I thought that we had resolved the width issue in a previous commmit. Maybe I was mistaken. @kentnek you good to take this one?

**Comment by kentnek** [comment]
@jakewies no we haven't solved that issue yet. Yeah I'll take this one

**Comment by msfjarvis** [comment]
Thanks for the quick fix @kentnek, things seem to work now!

**Comment by kentnek** [comment]
@msfjarvis yay i'm glad that it works for you!

**Comment by jakewies** [comment]
You da best @kentnek
