### ISSUE TITLE
deactivate the home page ?

### ISSUE THREAD

**Issue by Juu-** [jakewies/hugo-theme-codex#8]
Hi everyone,

Is it possible to deactivate the home please ?
It will be perfect for me to just have the blog section at the _home_

Thanks for your work,
Julien

**Comment by jakewies** [comment]
Hey @Juu- ! Thanks for checking out my project.

At the moment there isn't a convenient way of deactivating the home page. I also don't believe this to be a core tenet of this theme so I don't think it is in the cards for me to refactor the project to support such a feature.

However I still want to be of some service. The way I see it, you have a few options:

1. You can use this theme and override the `layouts/index.html`
2. You can clone this theme as a baseline for your own project, and reuse the layouts and styles for the blog page as a foundation.

**Comment by Juu-** [comment]
Hi @jakewies !

I will do your options and I think it will be great.

Thanks for your help and work,
Julien
