### ISSUE TITLE
Add a contact us icon with form popup

### ISSUE THREAD

**Issue by aldrineeinsteen** [jakewies/hugo-theme-codex#81]
Add a chat icon at the bottom with a API from getform.io for sending emails to configured email.

![image](https://user-images.githubusercontent.com/4903148/87457116-8246f780-c625-11ea-97ff-916b43d2bf10.png)

**Comment by kentnek** [comment]
I think this should best be applied to your own website as you need it, as most websites (especially those using this theme to be minimal) won't need that as a must-have feature.

**Comment by jakewies** [comment]
I agree. In general I think it's best if we limit new issues to issues themselves, and only propose a feature if it can be generalized for everyone's use case. The scope of this project is a personal blog, and a contact us section is outside of the scope. We appreciate the suggestion @aldrineeinsteen  , and your effort doesn't go unnoticed.
