### ISSUE TITLE
Twitter Meta Tags

### ISSUE THREAD

**Issue by ProfessorLogout** [jakewies/hugo-theme-codex#82]
Hi Everyone,

playing around with the meta tags codex generates I found the following:
https://github.com/jakewies/hugo-theme-codex/blob/a9a6f0c92ba89408a0527c5440ff21b30e382e10/layouts/_default/baseof.html#L22

As per the twitter card documentation this value should not be the url but the `@username of content creator`
https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup

On a similar note the twitter:site meta tag should not be a url either but `@username of website`.
https://github.com/jakewies/hugo-theme-codex/blob/a9a6f0c92ba89408a0527c5440ff21b30e382e10/layouts/_default/baseof.html#L21

Obviously both can, in many cases, be the same `@username`.

I would be happy to discuss and implement something to make the use of twitter tags more in line with the official twitter documentation.
As I am not deeply familiar with project layout or hugo templating in general I would love some help to get me started.
I will try to take a first stab at it later today.

From my understanding this would be require changes along the lines of
- Introduce new settings `twitter_author_handle` and `twitter_site_handle`
- Changing `_default/basof.html` to prefer the new settings for both fields and falling back to the `twitter` setting to not introduce backwards breaking changes
- Updating the documentation to explain the new behaviour

The twitter link used in the social icons should, from my understanding, not be affected by this at all.

**Comment by msfjarvis** [comment]
I invested some time into getting Twitter and Facebook metadata right, which is available as a theme component [here](https://github.com/msfjarvis/hugo-social-metadata), it might offer some pointers into getting things right in Codex. For my personal site I opted to override `baseof.html` and use the component directly since I already had things set up for it from the previous theme I used.

**Comment by jakewies** [comment]
This is interesting. I didn't realize we were doing things improperly. Thanks a ton for pointing this out @ProfessorLogout. It looks like we'll have to make some adjustments to `config.toml`, as right now we're only requiring the url to the user's Twitter profile. We also have to keep in mind that some people who use the theme may not have a twitter account at all.

@msfjarvis I'm poking through `hugo-social-metadata` and I would really like to use it in this theme. I've never configured a Hugo theme using modules before. It should be possible to use your lib in this project, yes?

**Comment by msfjarvis** [comment]
> @msfjarvis I'm poking through `hugo-social-metadata` and I would really like to use it in this theme. I've never configured a Hugo theme using modules before. It should be possible to use your lib in this project, yes?

I know that you can use a `go.mod` file to load themes into a site, but I'm not sure if that resolves dependencies recursively as well, or whether Hugo will fetch theme dependencies for users who either subtree merge or submodule their themes. Probably need to research a bit.

**Comment by jakewies** [comment]
@ProfessorLogout I spazzed out and didn't read the rest of your comment. I would love for you to take a stab. I can help you of course. Right now all this info lives in `layouts/_default/baseof.html`, which I believe you've already figured that out. We can use @msfjarvis project as reference and improve the implementation ourselves. What do you think?

**Comment by ProfessorLogout** [comment]
As mentioned in the PR: 
Long term I would like to decouple meta tags from the social icons and introduce the ability to change them per post.
Not limited to the two twitter tags changed here.

This would be similar to @msfjarvis efforts with `hugo-social-metadata` but based on my experience with opengraph.
What would you think is the better approach:
1) Contributing in `hugo-social-metadata` and trying to get the package included here (or at least mentioned in README.md for new users)
2) Contributing here and re-implementing some parts of @msfjarvis previous work

**Comment by jakewies** [comment]
I would love to have social metadata managed in a module such as your `hugo-social-metadata` @msfjarvis, and then we can consume that in this project. I've taken a look at #86 from @ProfessorLogout and I think it will get us over the hump right now. I agree that long term we should find a better solution. It's becoming a little messy in `config.toml`.

I am going to merge the PR and open a new issue regarding improvements to the metadata and loop you both in. Sound good?
