### ISSUE TITLE
Tags error when not using English

### ISSUE THREAD

**Issue by Yeonhoon** [jakewies/hugo-theme-codex#87]
Hi!

I'm one of hugo theme codex user. Thank you for making a great simple, minimal theme.

When I use the codex theme, I found there is an error in the tags.

Typing tags not using English(e.g., Korean, Chinense), there is an error like the photo below.

![image](https://user-images.githubusercontent.com/67638499/87739541-1332f400-c81b-11ea-8c40-e3751bb4218e.png)

I hope this issue can be fixed :>
Thank you!

**Comment by jakewies** [comment]
This is an interesting issue and definitely one I haven't come across before. I don't know yet how to manage it. I'll have to look into Hugo's language support.

**Comment by msfjarvis** [comment]
I have a separate problem where tags that contain spaces do not render onto the post, but I don't see anything obviously wrong with the code so I can't tell if it's a bug and where exactly is its source, Hugo or the theme. I'll look into it later today and raise an issue if it's a theme problem.

**Comment by jakewies** [comment]
Looks like we would need to have some additional language support. I don't have time to dive into this issue at the moment, and there doesn't seem to be a lot of push for this, but I'm going to keep it open. If anyone would like to tackle it, go for it!

**Comment by jakewies** [comment]
@Yeonhoon looks like this issue may now be solved with the addition of https://github.com/jakewies/hugo-theme-codex/pull/146#issuecomment-766177956 from @rbnis . Take a look if you are still interested in using the project.
