### ISSUE TITLE
Can't get navigation items to not be in alphabetical order

### ISSUE THREAD

**Issue by roddymunro** [jakewies/hugo-theme-codex#98]
Hello,

Very new to Hugo, but thought I'd give it a go.

I'm trying to get my navigation items to **not** be displayed in alphabetical order (ie. 'Home' before 'Blog'). However, I can't seem to achieve this. Based off of the source code here, I tried adding 'weight' to my pages in the config, but that didn't change anything.

How can I achieve this? Many thanks.

**Comment by dgnicholson** [comment]
@roddymunro Did you start with `weight = 0`? If it's set to `0` it will be considered not set and default to alphabetical ascending. Instead start at `1`. For example, the following will place _blog_ above _about_: 
```
[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"
  weight = 2

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"
  weight = 1
```

**Comment by roddymunro** [comment]
Ah! Thank you - that was it. Closing the issue.
